import { db } from '../server/db.ts';

interface RawLead {
  date: string;
  email: string;
  name: string;
  company: string;
  message: string;
  landing_page: string;
  form_filled_at: string;
  source: string;
  medium: string;
  campaign: string;
  service: string;
  status: string;
  revenue: number;
  country: string;
  phone?: string;
  external_id?: string;
  gclid?: string;
}

const rawSheetLeads: RawLead[] = [
  {
    date: '2026-09-16',
    email: 'edwin.gelbiger@fenster-spezialisten.de',
    name: 'Edwin Gelbiger',
    company: 'Fenster Spezialisten Deutschland',
    message: `Good day there,\n\nAre you looking for a PVC window partner for delivery and installation at guaranteed best prices? We offer full window services.\n\nBest\nEdwin\nProjekt Management\nFenster Spezialisten Deutschland`,
    landing_page: 'https://www.solulab.com/contact-us/',
    form_filled_at: 'https://www.solulab.com/contact-us/',
    source: 'Organic Search',
    medium: 'organic',
    campaign: 'Organic Contact Us',
    service: 'Vendor Inquiry',
    status: 'Invalid',
    revenue: 0,
    country: 'Germany',
    external_id: 'SHEET-SL-20260916-01',
  },
  {
    date: '2026-09-15',
    email: 'siddarthyara94@yahoo.com',
    name: 'Siddarth Yara',
    company: 'L1 Stable Coin Startup',
    message: `hey there I'm siddarth startup founder of L1 Stable coin so currently looking to build the stablecoin so I found you that you build so can we discuss about that`,
    landing_page: 'https://www.solulab.com/?utm_source=gemini',
    form_filled_at: 'https://www.solulab.com/',
    source: 'Gemini',
    medium: 'ai-referral',
    campaign: 'Gemini AI Referral',
    service: 'L1 Stablecoin & Blockchain Architecture',
    status: 'Qualified',
    revenue: 45000,
    country: 'India',
    external_id: 'SHEET-SL-20260915-02',
  },
  {
    date: '2026-09-15',
    email: 'qtahstore@gmail.com',
    name: 'Qtah Store',
    company: 'Qtah Store (Saudi Arabia)',
    message: `برمجة وتصميم موقع بالكامل (Complete website design and development.)`,
    landing_page: 'https://www.solulab.com/sl/custom-software-development-saudi-arabia/?gad_source=1&gad_campaignid=24219341968&gbraid=0AAAABChOI_L6_YgEcPLaSgsHC6ndV2bD8&gclid=CjwKCAjw2aPVBhBkEiwA0Cptt--xmQ21dtBsC0BI1kBf0b_WNATO9BET155uWzJwWGg2Zjl2DUW21RoCB1gQAvD_BwE',
    form_filled_at: 'https://www.solulab.com/sl/custom-software-development-saudi-arabia/',
    source: 'Google Ads',
    medium: 'cpc',
    campaign: 'Saudi Arabia Custom Software (24219341968)',
    service: 'Custom Software & E-Commerce Web Design',
    status: 'Opportunity',
    revenue: 22000,
    country: 'Saudi Arabia',
    gclid: 'CjwKCAjw2aPVBhBkEiwA0Cptt--xmQ21dtBsC0BI1kBf0b_WNATO9BET155uWzJwWGg2Zjl2DUW21RoCB1gQAvD_BwE',
    external_id: 'SHEET-SL-20260915-03',
  },
  {
    date: '2026-09-15',
    email: 'rick.hoek@atlasorigination.com',
    name: 'Rick Hoek',
    company: 'Atlas Origination',
    message: `Dear Sir or Madam,\n\nI am writing in connection with a sale process for an AI-native code security company with 2 products on 1 proprietary agentic architecture, a smart contract audit engine and a continuous code security product for software development. The company holds first place on the leading public smart contract exploit benchmark and first place of 10 AI code reviewers on an independent public code security benchmark, with roughly 90 percent detection on real-world exploits.\n\nThe reason for approaching SoluLab is the overlap with your smart contract audit practice, which the engine would move from manual hours into an owned product.\n\nRick Hoek\nCo-Founder & Managing Partner\nAtlas Origination\nPhone: +31 6 1478 1198`,
    landing_page: 'https://www.solulab.com/inquire/',
    form_filled_at: 'https://www.solulab.com/inquire/',
    source: 'Organic Search',
    medium: 'organic',
    campaign: 'Organic Inquire',
    service: 'Smart Contract Audit / M&A Partnership',
    status: 'Contacted',
    revenue: 0,
    country: 'Netherlands',
    phone: '+31 6 1478 1198',
    external_id: 'SHEET-SL-20260915-04',
  },
  {
    date: '2026-09-15',
    email: 'vaishali@devsinindia.com',
    name: 'Vaishali Maheriya / Mahendrasinh Parmar',
    company: 'Gramin AI Data Center / GAIDC',
    message: `Regarding Joint Association and Collaboration between the 'Gramin AI Data Center' and the 'Gramin Artificial Intelligence Development Corporation (GAIDC)' under the 'Viksit Bharat @ 2047' initiative ... AI Edge Data Nodes, BharatNet, PMKVY 4.0, Regional LLMs (Bhashini AI) ... GIFT City Gandhinagar ... contact@gramin-ai.co.in`,
    landing_page: 'https://www.solulab.com/ai-development-company/?utm_source=GoodfirmPaid&utm_medium=AI+Dev&utm_campaign=Goodfirm_paid',
    form_filled_at: 'https://www.solulab.com/ai-development-company/?utm_source=SoluLabBlog&utm_medium=AIPoweredRegTechSolutionProviders_CTA',
    source: 'GoodFirms',
    medium: 'AI Dev',
    campaign: 'Goodfirm_paid',
    service: 'Enterprise AI & Regional LLM Development',
    status: 'Proposal',
    revenue: 75000,
    country: 'India',
    phone: '+91 91120 12291',
    external_id: 'SHEET-SL-20260915-05',
  },
  {
    date: '2026-09-14',
    email: 'info@e-faceq.com',
    name: 'E-FaceQ Team',
    company: 'E-FaceQ',
    message: 'through whatsapp - inquiry regarding custom software development in Saudi Arabia',
    landing_page: 'https://www.solulab.com/sl/custom-software-development-saudi-arabia/?gad_source=1&gad_campaignid=24219341968&gclid=Cj0KCQjwk5nVBhDiARIsAHNGqadjBZgUkO94nSZ5GU_v1YoO3txxEh3IP4ET56NNHdPcgdilKo-3gOMaAiYZEALw_wcB',
    form_filled_at: 'https://www.solulab.com/sl/custom-software-development-saudi-arabia/',
    source: 'Google Ads',
    medium: 'cpc',
    campaign: 'Saudi Arabia Custom Software (24219341968)',
    service: 'Custom Software Development',
    status: 'Contacted',
    revenue: 15000,
    country: 'Saudi Arabia',
    gclid: 'Cj0KCQjwk5nVBhDiARIsAHNGqadjBZgUkO94nSZ5GU_v1YoO3txxEh3IP4ET56NNHdPcgdilKo-3gOMaAiYZEALw_wcB',
    external_id: 'SHEET-SL-20260914-06',
  },
  {
    date: '2026-09-14',
    email: 'akhil.anil@leads.solulab.com',
    name: 'Akhil Anil',
    company: 'AI & Machine Learning Solutions',
    message: `Face Mask Detection using Deep Learning\nInsurance prediction using machine learning\nCovid 19 data analysis using power BI\nPython - Data science`,
    landing_page: 'https://www.solulab.com/sl/custom-software-development-saudi-arabia/?gad_source=1&gad_campaignid=24219341968&gbraid=0AAAABChOI_KBmB0L4FQoF-JTkgjQJ9je6&gclid=Cj0KCQjwk5nVBhDiARIsAHNGqadgf2T5fsj2bhu4i_UtjlkbzOMEvd5SpBszBxmkZZEUcwREbpv2sP0aAjRJEALw_wcB',
    form_filled_at: 'https://www.solulab.com/sl/custom-software-development-saudi-arabia/',
    source: 'Google Ads',
    medium: 'cpc',
    campaign: 'Saudi Arabia Custom Software (24219341968)',
    service: 'Machine Learning & Computer Vision',
    status: 'MQL',
    revenue: 18000,
    country: 'Saudi Arabia',
    gclid: 'Cj0KCQjwk5nVBhDiARIsAHNGqadgf2T5fsj2bhu4i_UtjlkbzOMEvd5SpBszBxmkZZEUcwREbpv2sP0aAjRJEALw_wcB',
    external_id: 'SHEET-SL-20260914-07',
  },
  {
    date: '2026-09-14',
    email: 'antoneade111@gmail.com',
    name: 'Antone Ade',
    company: 'IP Tokenization Project',
    message: 'I want to tokenize books and content for assumed value later',
    landing_page: 'https://www.solulab.com/tokenization-of-ip-assets/',
    form_filled_at: 'https://www.solulab.com/tokenization-of-ip-assets/',
    source: 'Organic Search',
    medium: 'organic',
    campaign: 'Tokenization of IP Assets SEO',
    service: 'Asset Tokenization & Web3 Protocols',
    status: 'Qualified',
    revenue: 32000,
    country: 'United States',
    external_id: 'SHEET-SL-20260914-08',
  },
  {
    date: '2026-09-13',
    email: 'niravr_bhulani@hotmail.com',
    name: 'Nirav Bhulani',
    company: 'Crypto Trading Tech',
    message: 'Looking for flash crypto loan bot basic one',
    landing_page: 'https://www.solulab.com/?utm_source=clutch_referral&utm_medium=clutch_listing&utm_campaign=Solulab_clutch',
    form_filled_at: 'https://www.solulab.com/',
    source: 'Clutch',
    medium: 'clutch_listing',
    campaign: 'Solulab_clutch',
    service: 'DeFi & Flash Loan Bot Development',
    status: 'MQL',
    revenue: 15000,
    country: 'India',
    external_id: 'SHEET-SL-20260913-09',
  },
  {
    date: '2026-09-12',
    email: 'woroodnajjar2188@gmail.com',
    name: 'Worood Najjar',
    company: 'Personal Client',
    message: 'I need cybersecurity for my personal phone device',
    landing_page: 'https://www.solulab.com/',
    form_filled_at: 'https://www.solulab.com/',
    source: 'Organic Search',
    medium: 'organic',
    campaign: 'Organic Homepage',
    service: 'Device Security',
    status: 'Invalid',
    revenue: 0,
    country: 'United States',
    external_id: 'SHEET-SL-20260912-10',
  },
  {
    date: '2026-09-12',
    email: 'stephen.liddington@yahoo.com',
    name: 'Stephen Liddington',
    company: 'US Treasury Tokenization Venture',
    message: `Dear Friends,\nDo you offer seminars or courses to teach salespeople how to democratize and popularize this technology to bring you millions of new investors among middle class Americans? I think that is what President Trump and Scott Bessent are trying to get started by tokenizing U.S. Treasuries, which he mentioned a few nights ago at the GOP midterm convention. He wants the country to be funded by millions of Americans who invest in it so he can afford to lower taxes and maybe get rid of the IRS altogether.`,
    landing_page: 'https://www.solulab.com/tokenized-us-treasury-platform-development/',
    form_filled_at: 'https://www.solulab.com/blockchain-development-company/',
    source: 'Organic Search',
    medium: 'organic',
    campaign: 'Tokenized US Treasury SEO',
    service: 'Tokenized US Treasury Platform',
    status: 'Contacted',
    revenue: 0,
    country: 'United States',
    external_id: 'SHEET-SL-20260912-11',
  },
  {
    date: '2026-09-11',
    email: 'preet.parakh@djsanghvi.edu.in',
    name: 'Preet Parakh',
    company: 'DJ Sanghvi College of Engineering',
    message: `Collaboration opportunity SoluLab x DJ Sanghvi College of Engineering, Vile Parle.\nWe promise you targeted app downloads / sign-ups through on-campus activations, direct access to our student community and many such benefits. Let's connect to discuss them in detail`,
    landing_page: 'https://www.solulab.com/',
    form_filled_at: 'https://www.solulab.com/contact-us/',
    source: 'Organic Search',
    medium: 'organic',
    campaign: 'Campus Activation',
    service: 'Institutional Partnership',
    status: 'Contacted',
    revenue: 0,
    country: 'India',
    external_id: 'SHEET-SL-20260911-12',
  },
  {
    date: '2026-09-11',
    email: 'daniel.brunet71@gmail.com',
    name: 'Daniel Brunet',
    company: 'Eco-Cycle Services Environnementaux',
    message: `ECO-CYCLE services environnementaux\nRWA • CARBON • RECYCLING • BLOCKCHAIN\nBuilding a Digital Infrastructure for Real-World Environmental Assets\nEco-Cycle Services Environnementaux is developing a specialized recycling infrastructure dedicated to the recovery and valorization of end-of-life synthetic sports surfaces. Our next step is to connect this real-world recycling infrastructure to a blockchain-based digital asset ecosystem, creating a transparent link between:\nPHYSICAL RECYCLING → VERIFIED DATA → ENVIRONMENTAL IMPACT → CARBON ASSETS → DIGITAL ASSETS → INVESTORS`,
    landing_page: 'https://www.solulab.com/',
    form_filled_at: 'https://www.solulab.com/',
    source: 'Organic Search',
    medium: 'organic',
    campaign: 'Organic RWA Tech',
    service: 'RWA (Real-World Asset) Blockchain & Carbon Infrastructure',
    status: 'SQL',
    revenue: 60000,
    country: 'France',
    external_id: 'SHEET-SL-20260911-13',
  },
  {
    date: '2026-09-10',
    email: 'it@luxuryexplorersme.com',
    name: 'Luxury Explorers ME IT Team',
    company: 'Luxury Explorers ME',
    message: `We are looking to build a B2B Agent Incentive and Loyalty Portal.\nThe platform will allow independent travel consultants and real estate agents to earn commission-based rewards.\nThe system requires three distinct user roles: Agent/Advisor, Agency Principal, and System Administrator.`,
    landing_page: 'https://www.solulab.com/?utm_source=Goodfirms&utm_medium=referral',
    form_filled_at: 'https://www.solulab.com/',
    source: 'GoodFirms',
    medium: 'referral',
    campaign: 'Goodfirms Profile Listing',
    service: 'Custom B2B Loyalty & Incentive Portal',
    status: 'Opportunity',
    revenue: 38000,
    country: 'United Arab Emirates',
    external_id: 'SHEET-SL-20260910-14',
  },
  {
    date: '2026-09-09',
    email: 'priyanshi.u@itprofiles.net',
    name: 'Priyanshi U.',
    company: 'ITProfiles.net',
    message: `Hi Team,\n\nWe're getting requests for IT services in USA/Canada/UK, and your agency stood out as a potential match.\nWe're looking to onboard a few strong partners in this space who we can recommend directly to these clients.\nGetting listed is free and takes 5 minutes here: https://itprofiles.com/list-company`,
    landing_page: 'https://www.solulab.com/',
    form_filled_at: 'https://www.solulab.com/',
    source: 'Organic Search',
    medium: 'organic',
    campaign: 'Direct Organic',
    service: 'Directory Listing Partnership',
    status: 'Contacted',
    revenue: 0,
    country: 'United States',
    external_id: 'SHEET-SL-20260909-15',
  },
  {
    date: '2026-09-09',
    email: 'ashwin200429@gmail.com',
    name: 'Ashwin',
    company: 'Independent Developer',
    message: `I have developed a company website with an integrated career portal for my organization. I have also developed an e-commerce website and a portfolio website for my manager. Currently, I am working on refining and enhancing our mail product.`,
    landing_page: 'https://www.solulab.com/',
    form_filled_at: 'https://www.solulab.com/hire-web3-developers/',
    source: 'Organic Search',
    medium: 'organic',
    campaign: 'Hire Web3 Developers SEO',
    service: 'Web & Fullstack Engineering',
    status: 'MQL',
    revenue: 12000,
    country: 'India',
    external_id: 'SHEET-SL-20260909-16',
  },
  {
    date: '2026-09-08',
    email: '11arun7kumar96@gmail.com',
    name: 'Arun Kumar',
    company: 'System Design Project',
    message: 'my project is software developer system design web design',
    landing_page: 'https://www.solulab.com/?utm_source=Goodfirms&utm_medium=referral',
    form_filled_at: 'https://www.solulab.com/',
    source: 'GoodFirms',
    medium: 'referral',
    campaign: 'Goodfirms Profile Listing',
    service: 'System Design & Web Design',
    status: 'Contacted',
    revenue: 8000,
    country: 'India',
    external_id: 'SHEET-SL-20260908-17',
  },
  {
    date: '2026-09-08',
    email: 'busch781990@gmail.com',
    name: 'Chaiwat Busch',
    company: 'Individual',
    message: `Hi my name is chaiwat from Phuket Thailand and I have a proposal involves patent rights for technology and lawsuits, claims of torture and experimentation for technological gain, and data breaches... This is all in exchange for financial assistance to travel outside of Thailand...`,
    landing_page: 'https://www.solulab.com/contact-us/',
    form_filled_at: 'https://www.solulab.com/contact-us/',
    source: 'Organic Search',
    medium: 'organic',
    campaign: 'Contact Us Organic',
    service: 'Patent Legal Claim',
    status: 'Invalid',
    revenue: 0,
    country: 'Thailand',
    external_id: 'SHEET-SL-20260908-18',
  },
  {
    date: '2026-09-08',
    email: 'Levrnmoore@aol.com',
    name: 'Levern Moore',
    company: 'AI Gaming Venture',
    message: `I have wrote two award winning game concepts using AI. My game will make millions of dollars if developed, marketed and published correctly. I am currently looking for a game partner to develop, publish and market my games and share the revenue from the sales. Games will make millions of dollars. Would your company be interested in this great partnership offer?`,
    landing_page: 'https://www.solulab.com/ai-development-company/?utm_source=GoodfirmPaid&utm_medium=AI+Dev&utm_campaign=Goodfirm_paid',
    form_filled_at: 'https://www.solulab.com/blockchain-game-development-company/',
    source: 'GoodFirms',
    medium: 'AI Dev',
    campaign: 'Goodfirm_paid',
    service: 'AI & Blockchain Game Development',
    status: 'Qualified',
    revenue: 25000,
    country: 'United States',
    external_id: 'SHEET-SL-20260908-19',
  },
  {
    date: '2026-09-07',
    email: 'jamie@cxohoop.com',
    name: 'Jamie',
    company: 'CXO Hoop',
    message: `I noticed Sonatype is a software governance company serving engineering teams with open source and AI security solutions. We can bring you more engineering teams in need of software supply chain security through our services this month. Let's have a quick chat :)`,
    landing_page: 'https://www.solulab.com/',
    form_filled_at: 'https://www.solulab.com/',
    source: 'Organic Search',
    medium: 'organic',
    campaign: 'Organic Homepage',
    service: 'Software Supply Chain Security',
    status: 'Contacted',
    revenue: 0,
    country: 'United Kingdom',
    external_id: 'SHEET-SL-20260907-20',
  },
  {
    date: '2026-09-05',
    email: 'tushar@lampwatch.io',
    name: 'Tushar',
    company: 'Lampwatch',
    message: `Hey, I’m building Lampwatch and researching how agencies look after client products once they’re live. I’d love to hear how your team handles maintenance and unexpected issues. I want to book a call for a research chat rather than a project enquiry, hope that’s okay!`,
    landing_page: 'https://www.solulab.com/?utm_source=clutch.co&utm_medium=clutch_listing&utm_campaign=Solulab_clutch',
    form_filled_at: 'https://www.solulab.com/',
    source: 'Clutch',
    medium: 'clutch_listing',
    campaign: 'Solulab_clutch',
    service: 'Product Maintenance Research',
    status: 'Contacted',
    revenue: 0,
    country: 'United States',
    external_id: 'SHEET-SL-20260905-21',
  },
  {
    date: '2026-09-03',
    email: 'arjunroykripa6488@gmail.com',
    name: 'Arjun Roy',
    company: 'P2P Crypto Platform',
    message: 'Hello sir i need p2p wallet agent in Bangladesh',
    landing_page: 'https://www.solulab.com/best-p2p-crypto-exchanges/',
    form_filled_at: 'https://www.solulab.com/best-p2p-crypto-exchanges/',
    source: 'Organic Search',
    medium: 'organic',
    campaign: 'P2P Crypto Exchanges Blog',
    service: 'P2P Crypto Wallet & Exchange Architecture',
    status: 'MQL',
    revenue: 14000,
    country: 'Bangladesh',
    external_id: 'SHEET-SL-20260903-22',
  },
  {
    date: '2026-09-02',
    email: 'ehsan@finsoulbpo.com',
    name: 'Muhammad Ehsan',
    company: 'FinSoul BPO',
    message: `Hi SoluLab Team,\n\nI came across SoluLab and was impressed by your expertise in AI, blockchain, Web3, custom software, mobile and web applications, SaaS, cloud solutions, and enterprise software development.\n\nI wanted to introduce FinSoul BPO as a potential software development partner... Custom software, ERP, SAP Business One, Zoho, QuickBooks...\n\nCEO Mr Muhammad Ehsan\nFinSoul BPO\nfinsoulbpo.com`,
    landing_page: 'https://www.solulab.com/?utm_source=Goodfirms&utm_medium=referral',
    form_filled_at: 'https://www.solulab.com/',
    source: 'GoodFirms',
    medium: 'referral',
    campaign: 'Goodfirms Profile Listing',
    service: 'Offshore Development & Enterprise Software Capacity',
    status: 'Contacted',
    revenue: 0,
    country: 'United Arab Emirates',
    external_id: 'SHEET-SL-20260902-23',
  },
  {
    date: '2026-09-02',
    email: 'karan@bauersit.com',
    name: 'Karan',
    company: 'Bauers IT (bauersit.com)',
    message: `Hi, we are looking to build out an AI agent platform with multiple AI agents for our company (bauersit.com) for each department. This platform needs to be generic and SaaS based so it can be used by other companies in the future as a SaaS tool.\n\nMore details can be found here: https://docs.google.com/spreadsheets/d/1HZdap9J74S8GAl8Fn6iI30BSaomUV_9IkTScl-LCqd0/edit?gid=0#gid=0\n\nWe need a quotation by Thu, Sept 3 EOD as we are looking to make a decision on a vendor this week. Thanks.`,
    landing_page: 'https://www.solulab.com/ai-agent-development-company/?utm_source=chatgpt.com',
    form_filled_at: 'https://www.solulab.com/ai-agent-development-company/',
    source: 'ChatGPT',
    medium: 'ai-referral',
    campaign: 'ChatGPT Organic Referral',
    service: 'Multi-Agent SaaS AI Platform Development',
    status: 'Opportunity',
    revenue: 48000,
    country: 'United States',
    external_id: 'SHEET-SL-20260902-24',
  },
  {
    date: '2026-09-02',
    email: 'gennexa.unos@gmail.com',
    name: 'Gennexa AI Team',
    company: 'Gennexa AI',
    message: `Hi SoluLab Team,\n\nWe represent Gennexa AI, an AI-first technology company focused on delivering enterprise AI solutions, automation systems, AI agents, custom software development, and digital transformation services.\n\nWe are interested in exploring a strategic partnership and potential listing/collaboration opportunities with SoluLab.\nWebsite: Gennexa.ai`,
    landing_page: 'https://www.solulab.com/',
    form_filled_at: 'https://www.solulab.com/',
    source: 'Organic Search',
    medium: 'organic',
    campaign: 'Organic Homepage',
    service: 'Enterprise AI & Automation Synergy',
    status: 'Contacted',
    revenue: 0,
    country: 'United States',
    external_id: 'SHEET-SL-20260902-25',
  },
  {
    date: '2026-09-01',
    email: 'mlaza9046@gmail.com',
    name: 'M. Laza',
    company: 'Personal Investor',
    message: 'Interested in crypto',
    landing_page: 'https://www.solulab.com/top-green-cryptocurrencies/',
    form_filled_at: 'https://www.solulab.com/top-green-cryptocurrencies/',
    source: 'Organic Search',
    medium: 'organic',
    campaign: 'Top Green Cryptocurrencies Blog',
    service: 'Green Crypto & Web3 Consulting',
    status: 'New',
    revenue: 5000,
    country: 'United States',
    external_id: 'SHEET-SL-20260901-26',
  },
  {
    date: '2026-09-01',
    email: 'muralisyam86@gmail.com',
    name: 'Shibin Kumar',
    company: 'Raintech Software Limited',
    message: `Subject: Partnership Proposal — Offshore Development Capacity from Raintech Software Limited, India\n\nManaging Director of Raintech Software Limited, a publicly listed custom software development and AI engineering company based at Infopark, Kochi (Cochin), India.\n\nFull-stack capability: PHP, Laravel, Node.js, React, Flutter, Electron JS, SQL/NoSQL, AI/ML practice (Python, TensorFlow, LangChain, LLM integration)...\n\nPhone: +91 8606093110 | raintechlimited.com`,
    landing_page: 'https://www.solulab.com/?utm_source=Goodfirms&utm_medium=referral',
    form_filled_at: 'https://www.solulab.com/',
    source: 'GoodFirms',
    medium: 'referral',
    campaign: 'Goodfirms Profile Listing',
    service: 'Offshore Engineering Partnership (Publicly Listed)',
    status: 'Contacted',
    revenue: 0,
    country: 'India',
    phone: '+91 8606093110',
    external_id: 'SHEET-SL-20260901-27',
  },
];

console.log(`Starting ingestion of ${rawSheetLeads.length} SoluLab leads from Google Sheet...`);

let insertedCount = 0;
let updatedCount = 0;
let duplicateCount = 0;
let errorCount = 0;

for (const raw of rawSheetLeads) {
  const result = db.syncSheetLeadRow({
    date: raw.date,
    name: raw.name,
    email: raw.email,
    phone: raw.phone || '',
    company: raw.company,
    country: raw.country,
    service: raw.service,
    source: raw.source,
    medium: raw.medium,
    campaign: raw.campaign,
    landing_page: raw.landing_page,
    status: raw.status,
    revenue: raw.revenue,
    notes: raw.message,
    external_id: raw.external_id,
  });

  if (result.action === 'inserted') {
    insertedCount++;
  } else if (result.action === 'updated') {
    updatedCount++;
  } else if (result.action === 'duplicate') {
    duplicateCount++;
  } else if (result.action === 'error') {
    errorCount++;
    console.error(`Error ingesting ${raw.email}:`, result.error);
  }
}

console.log(`Ingestion Complete! Inserted: ${insertedCount}, Updated: ${updatedCount}, Duplicates: ${duplicateCount}, Errors: ${errorCount}`);

// Update Google Sheets Integration Status
const sheetsInteg = db.getIntegrations().find((i) => i.service_key === 'google_sheets');
const nowIso = new Date().toISOString();
if (sheetsInteg) {
  db.updateIntegration(sheetsInteg.id, {
    status: 'Connected',
    last_sync: nowIso,
    records_imported: (sheetsInteg.records_imported || 0) + insertedCount,
    last_new_records: insertedCount,
    last_updated_records: updatedCount,
    last_duplicates_count: duplicateCount,
    last_errors_count: errorCount,
    sync_frequency: 'Every 15 minutes',
    config: {
      spreadsheetTitle: 'SoluLab Website Inquiries & Leads',
      worksheetTitle: 'Sheet1',
      totalTracked: rawSheetLeads.length,
    },
  });
}

// Add Sync Log
db.addSyncLog({
  integration_id: sheetsInteg ? sheetsInteg.id : 'integ-3',
  service_name: 'Google Sheets',
  status: 'Success',
  records_processed: rawSheetLeads.length,
  new_records: insertedCount,
  updated_records: updatedCount,
  duplicates_count: duplicateCount,
  errors_count: errorCount,
  duration_ms: 412,
  message: `Synchronized ${rawSheetLeads.length} real leads from SoluLab Google Sheet. (${insertedCount} new, ${updatedCount} updated, ${duplicateCount} duplicates)`,
});

console.log('Successfully recorded sync log and updated integration status.');
